name: flutter_mcu_wiki
version: 1.0.0+1
publish_to: none
description: MCU films wikipedia.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 1.1.0
  google_fonts: 5.1.0
  cached_network_image: ^3.2.3

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

